Add Markdown Support
mqnguyen5/mini-ssg pull request #9
Opened 2021-09-21 22:03 UTC by hlavu

Hi Quan, I have completed the code for the markdown support. Please review it and let me know If you want me to change any part.

2021-09-21 22:33 UTC, mqnguyen5 requested changes
Overall, the pull request looks great. However, there are some things that should be changed and I have left comments so you can have a look.

2021-09-21 22:33 UTC, mqnguyen5 commented on utils/generateHTML.js
> +var htmlBody = "";
You should change this line into `let`, as using `var` might cause some unexpected behaviour

2021-09-21 22:33 UTC, mqnguyen5 commented on utils/generateHTML.js
> +          if (para.match(/(?<!#)#{1}\s/)) {
From the Mozilla [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match):
> `String.match()` returns an Array whose contents depend on the presence or absence of the global (g) flag, or **null** if no matches are found. 

Thus, I suggest changing both the `if` and `else if` conditions to:
```js
if ([statement] != null) 
```

2021-09-22 03:55 UTC, hlavu commented
That's great, I will change them.

2021-09-22 04:03 UTC, mqnguyen5 reviewed
Everything looks great! Thanks for the contribution.

2021-09-22 04:04 UTC, merged